# Generated by Django 4.1.1 on 2022-10-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
