# Generated by Django 4.1.1 on 2022-10-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150, null=True)),
                ('firstname', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('lastname', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('gender', models.CharField(default='Male', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
