# Generated by Django 4.1.1 on 2022-10-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_userprofile_remove_account_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
