# Generated by Django 4.1.1 on 2022-10-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/defaultuser/userjpg', upload_to='userprofile'),
        ),
    ]
