# Generated by Django 4.1.1 on 2022-10-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='defaultuser/userjpg', upload_to='userprofile'),
        ),
    ]
