# Generated by Django 4.1.1 on 2022-11-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0003_alter_comments_user_comment'),
        ('Order', '0002_alter_order_useroder'),
        ('Account', '0010_remove_userprofile_main_user_account_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
