# Generated by Django 4.1.1 on 2022-11-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_account_managers_remove_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
