# Generated by Django 4.1.1 on 2022-10-24 21:42

import Product.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0007_remove_category_parenttitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to=Product.models.UploadImage)),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('rate', models.CharField(blank=True, choices=[('High', 'High'), ('Low', 'Low'), ('Affordable', 'Affordable')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categories.category')),
                ('Pro_Detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
