# Generated by Django 4.1.1 on 2022-10-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
