# Generated by Django 4.1.1 on 2022-10-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0007_remove_category_parenttitle_and_more'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Low', 'Low'), ('Affordable', 'Affordable')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categories.category')),
                ('Pro_Detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
