# Generated by Django 4.1.1 on 2022-10-24 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0007_remove_category_parenttitle_and_more'),
        ('Product', '0002_delete_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('XS', 'XS'), ('SM', 'SM'), ('LG', 'LG'), ('XXL', 'XXL')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categories.category')),
                ('Pro_Detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
