# Generated by Django 4.1.1 on 2022-10-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_price_product_rate_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('SM', 'SM'), ('LG', 'LG'), ('XXL', 'XXL')], max_length=50, null=True),
        ),
    ]
