# Generated by Django 4.1.1 on 2022-10-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SizeColor', '0001_initial'),
        ('Product', '0006_productdetail_pro_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='Pro_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SizeColor.colors'),
        ),
    ]
