# Generated by Django 4.1.1 on 2022-11-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_productdetail_pro_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Tommy', max_length=50),
        ),
    ]
