# Generated by Django 4.1.1 on 2022-11-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0005_alter_comments_user_comment'),
        ('Product', '0008_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='Pro_Comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comments.comments'),
        ),
    ]
