# Generated by Django 4.1.1 on 2022-10-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SizeRate', models.CharField(choices=[('black', 'black'), ('grey', 'grey'), ('red', 'red'), ('blue', 'blue'), ('brown', 'brown'), ('white', 'white')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SizeRate', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('XS', 'XS'), ('SM', 'SM'), ('LG', 'LG'), ('XXL', 'XXL')], max_length=50)),
            ],
        ),
    ]
