# Generated by Django 4.1.1 on 2022-10-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SizeColor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='SizeRate',
            new_name='Color_Rate',
        ),
    ]
