# Generated by Django 4.1.1 on 2022-11-02 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comments', '0003_alter_comments_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='User_Comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
