# Generated by Django 4.1.1 on 2022-11-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_remove_productdetail_pro_comment'),
        ('Comments', '0005_alter_comments_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='DataCreated',
        ),
        migrations.CreateModel(
            name='Product_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataCreated', models.DateTimeField(auto_now_add=True)),
                ('ItemComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.comments')),
                ('ItemProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productdetail')),
            ],
        ),
    ]
