# Generated by Django 4.1.1 on 2022-10-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentCategory', models.CharField(choices=[('Man', 'Man'), ('Women', 'Women'), ('Electronic', 'Electronic')], max_length=50)),
                ('ParentTitle', models.CharField(choices=[('Man', 'Man'), ('Women', 'Women'), ('Electronic', 'Electronic')], max_length=50)),
            ],
        ),
    ]
