# Generated by Django 4.1.1 on 2022-10-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Parentitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Categories.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ParentTitle',
            field=models.CharField(max_length=50),
        ),
    ]
