# Generated by Django 4.1.1 on 2022-10-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0004_alter_category_parenttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ParentTitle',
            field=models.CharField(blank=True, choices=[('Tshirt', 'Tshirt'), ('Pants', 'Pants'), ('Accessories', 'Accessories'), ('Bags', 'Bags')], max_length=50, null=True),
        ),
    ]
