# Generated by Django 4.1.1 on 2022-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0005_alter_category_parenttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ParentCategory',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Women', 'Women'), ('Electronic', 'Electronic')], max_length=50, null=True),
        ),
    ]
