# Generated by Django 4.1.1 on 2022-10-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0006_alter_category_parentcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ParentTitle',
        ),
        migrations.AlterField(
            model_name='category',
            name='ParentCategory',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Women', 'Women'), ('Electronic', 'Electronic'), ('Tshirt', 'Tshirt'), ('Pants', 'Pants'), ('Accessories', 'Accessories'), ('Bags', 'Bags')], max_length=50, null=True),
        ),
    ]
