# Generated by Django 4.1.1 on 2022-10-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0007_remove_category_parenttitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ParentCategory',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Women', 'Women'), ('Electronic', 'Electronic'), ('Tshirt', 'Tshirt'), ('Pants', 'Pants'), ('Accessories', 'Accessories'), ('Bags', 'Bags'), ('Shoes', 'Shoes'), ('Jacket', 'Jacket')], max_length=50, null=True),
        ),
    ]
