# Generated by Django 4.1.1 on 2022-11-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_remove_userprofile_main_user_account_city_and_more'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='UserOder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.account'),
        ),
    ]
