# Generated by Django 4.1.1 on 2022-11-02 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0002_alter_order_useroder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='UserOder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
