# Generated by Django 4.1.1 on 2022-11-02 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_account_managers_remove_account_email_and_more'),
        ('Order', '0003_alter_order_useroder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='UserOder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.account'),
        ),
    ]
