# Generated by Django 4.1.1 on 2022-11-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_useroder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_count',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
