# Generated by Django 4.1.1 on 2022-11-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_orderdetail_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='purchase',
            field=models.BooleanField(default=False),
        ),
    ]
