# Generated by Django 4.1.1 on 2022-11-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_shippingdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_count',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
