# Generated by Django 4.1.1 on 2022-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_alter_orderdetail_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.BooleanField(default=False),
        ),
    ]
