# Generated by Django 4.1.1 on 2022-11-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_order_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_count',
            field=models.IntegerField(default=1),
        ),
    ]
