# Generated by Django 4.1.1 on 2022-11-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_cardspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
