# Generated by Django 4.1.1 on 2022-11-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_orderdetail_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardspecification',
            name='CardMonth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cardspecification',
            name='CardYear',
            field=models.IntegerField(),
        ),
    ]
