# Generated by Django 4.1.1 on 2022-11-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_alter_cardspecification_cardmonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OrderNumber',
            field=models.IntegerField(default=0),
        ),
    ]
